name: attendance
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  attendance_shared:
    path: ../attendance_shared
  
  cupertino_icons: ^1.0.2

  flutter_screenutil:
  google_fonts:
  rounded_loading_button:
  flutter_spinkit:
  camera: ^0.7.0+4
  fluttertoast: 
  path_provider:
  video_player:
  quiver:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.3
  freezed: 0.12.2
  injectable_generator:
  lint:
  json_serializable:
  auto_route_generator:


flutter:

  uses-material-design: true
  assets:
    - images/
